services:
  app:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - ./docker/containers/node:/home/vscode
    working_dir: /app
    user: vscode