services:
  app:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8044:3000"
    command: sh setup.sh && npm install && node server.js
    volumes:
      - .:/app
      - ./docker/containers/node:/home/vscode
    working_dir: /app
    user: vscode
